const styles = {
  shell: { display: 'flex', flexDirection: 'column', height: '100vh', background: '#f5f4f0', color: '#3a3a33' },
  root: { display: 'flex', flex: 1, overflow: 'hidden', background: '#f5f4f0', color: '#3a3a33' },
  // ── title bar ──────────────────────────────────────────────────────────────
  titleBar: { height: 40, flexShrink: 0, display: 'flex', alignItems: 'center', background: '#f3f2ee', WebkitAppRegion: 'drag', userSelect: 'none' },
  titleBarBorder: { height: 1, flexShrink: 0, background: '#e5e3dc' },
  titleBarLeft: { display: 'flex', alignItems: 'center', gap: 2, paddingLeft: 12, WebkitAppRegion: 'no-drag' },
  titleBarCenter: { flex: 1, display: 'flex', justifyContent: 'center', alignItems: 'center', WebkitAppRegion: 'drag' },
  titleBarIconBtn: { background: 'none', border: 'none', cursor: 'pointer', color: '#3a3a33', fontSize: 16, width: 28, height: 28, borderRadius: 6, display: 'flex', alignItems: 'center', justifyContent: 'center', WebkitAppRegion: 'no-drag' },
  sidebar: { background: '#f3f2ee', display: 'flex', flexDirection: 'column', gap: 8, padding: '12px 0 12px 12px', overflow: 'hidden', flexShrink: 0 },
  resizeHandle: { width: 4, cursor: 'col-resize', background: 'transparent', borderRight: '1px solid #e5e3dc', flexShrink: 0 },
  folderPath: { fontSize: 12, color: '#8c8c84', overflow: 'hidden', textOverflow: 'ellipsis', whiteSpace: 'nowrap' },
  fileList: { flex: 1, overflowY: 'auto', display: 'flex', flexDirection: 'column', marginTop: 4 },
  btn: { border: 'none', borderRadius: 6, padding: '6px 10px', cursor: 'pointer', fontSize: 12 },
  folderBtn: { display: 'flex', alignItems: 'center', gap: 6, background: '#1a1a19', color: '#ffffff', border: '1px solid #1a1a19', borderRadius: 8, padding: '6px 10px', fontSize: 12, fontWeight: 500, cursor: 'pointer', width: '100%' },
  folderMenu: { position: 'absolute', top: 'calc(100% + 6px)', left: 0, right: 0, background: '#ffffff', border: '1px solid #e0deda', borderRadius: 12, boxShadow: '0 4px 20px rgba(0,0,0,0.12)', overflow: 'hidden', zIndex: 200, minWidth: 220 },
  folderMenuSection: { fontSize: 11, fontWeight: 600, color: '#8c8c84', padding: '10px 14px 4px', letterSpacing: 0.3, textTransform: 'uppercase' },
  folderMenuItem: { display: 'flex', alignItems: 'flex-start', gap: 10, padding: '9px 14px', cursor: 'pointer', transition: 'background 0.1s' },
  folderMenuName: { fontSize: 13, fontWeight: 600, color: '#3a3a33', lineHeight: 1.3 },
  folderMenuPath: { fontSize: 11, color: '#8c8c84', marginTop: 1, overflow: 'hidden', textOverflow: 'ellipsis', whiteSpace: 'nowrap' },
  folderMenuDivider: { height: 1, background: '#f0ede8', margin: '4px 0' },
  main: { flex: 1, display: 'flex', flexDirection: 'column', overflow: 'hidden', background: '#f5f4f0' },
  badge: { fontSize: 11, color: '#166534', background: '#dcfce7', border: '1px solid #bbf7d0', borderRadius: 12, padding: '2px 8px' },
  messages: { flex: 1, overflowY: 'auto', padding: '20px 80px 12px', display: 'flex', flexDirection: 'column', gap: 14, background: '#f5f4f0' },
  empty: { color: '#3a3a33', fontSize: 13, margin: 'auto', textAlign: 'center', lineHeight: 2, display: 'flex', flexDirection: 'column', alignItems: 'center' },
  message: { display: 'flex', flexDirection: 'column', gap: 4, maxWidth: '100%' },
  messageUser: { alignSelf: 'flex-end', alignItems: 'flex-end' },
  messageAssistant: { alignSelf: 'flex-start', alignItems: 'flex-start' },
  messageRole: { fontSize: 10, color: '#8c8c84', letterSpacing: 1 },
  messageContent: { background: '#ffffff', border: '1px solid #e5e3dc', borderRadius: 10, padding: '12px 16px', lineHeight: 1.6, fontSize: 13, color: '#3a3a33' },
  messageContentUser: { background: '#1a1a19', border: '1px solid #1a1a19', color: '#e8e6df', borderRadius: 10, padding: '12px 16px', lineHeight: 1.6, fontSize: 13 },
  copyBtn: { position: 'absolute', top: -26, right: 0, background: 'none', border: 'none', cursor: 'pointer', color: '#3a3a33', fontSize: 16, padding: '2px 6px', borderRadius: 4, zIndex: 1 },
  copyBtnLarge: { display: 'flex', alignItems: 'center', gap: 6, background: '#1a1a19', color: '#ffffff', border: 'none', borderRadius: 8, padding: '7px 14px', fontSize: 13, fontWeight: 600, cursor: 'pointer', marginBottom: 8, alignSelf: 'flex-start' },
  userText: { whiteSpace: 'pre-wrap', wordBreak: 'break-word', fontFamily: 'system-ui, sans-serif' },
  markdownBody: { fontFamily: 'system-ui, sans-serif', fontSize: 13, lineHeight: 1.7, color: '#3a3a33', wordBreak: 'break-word' },
  spinnerChar: { fontSize: 18, color: '#d97706', fontStyle: 'normal' },
  thinkingInline: { display: 'flex', alignItems: 'center', gap: 8 },
  thinkingModel: { fontSize: 15, fontWeight: 600, color: '#3a3a33' },
  thinkingIcon: { fontSize: 16, lineHeight: 1 },
  thinkingText: { fontSize: 15, color: '#3a3a33', fontStyle: 'italic' },
  thinkingMeta: { fontSize: 12, color: '#3a3a33', fontStyle: 'normal', opacity: 0.5 },
  inputWrap: { padding: '8px 80px 16px', background: '#f5f4f0', display: 'flex', flexDirection: 'column' },
  inputBox: { background: '#ffffff', border: 'none', borderRadius: 16, overflow: 'visible', transition: 'box-shadow 0.15s' },
  inputBoxFocused: { boxShadow: '0 0 0 1.5px #d5d2ca' },
  textarea: { display: 'block', width: '100%', background: 'transparent', color: '#3a3a33', border: 'none', padding: '16px 16px 10px', fontSize: 15, fontFamily: 'system-ui, -apple-system, sans-serif', resize: 'none', outline: 'none', lineHeight: 1.6, minHeight: 110, maxHeight: 320, overflowY: 'auto', boxSizing: 'border-box' },
  inputFooter: { display: 'flex', alignItems: 'center', justifyContent: 'space-between', padding: '8px 12px 10px', borderTop: '1px solid #f0ede8' },
  modelSelect: { background: 'transparent', color: '#5c5c54', border: '1px solid #e0deda', borderRadius: 8, padding: '4px 8px', fontSize: 12, cursor: 'pointer', maxWidth: 160, outline: 'none' },
  modelBtn: { display: 'flex', alignItems: 'center', gap: 6, background: '#ffffff', color: '#3a3a33', border: '1px solid #e0ddd6', borderRadius: 4, padding: '8px 16px', fontSize: 13, fontWeight: 500, cursor: 'pointer', whiteSpace: 'nowrap', boxShadow: '0 1px 2px rgba(0,0,0,0.04)' },
  modelMenu: { position: 'absolute', bottom: 'calc(100% + 6px)', right: 0, background: '#ffffff', border: '1px solid #e0deda', borderRadius: 12, boxShadow: '0 -4px 20px rgba(0,0,0,0.12)', overflow: 'hidden', zIndex: 200, minWidth: 180 },
  sendBtn: { width: 30, height: 30, borderRadius: 9, border: 'none', background: '#e8e6e0', color: '#9c9a94', fontSize: 16, cursor: 'default', display: 'flex', alignItems: 'center', justifyContent: 'center', transition: 'background 0.15s, color 0.15s', flexShrink: 0 },
  sendBtnActive: { background: '#1a1a19', color: '#ffffff', cursor: 'pointer' },
  stopBtn: { width: 30, height: 30, borderRadius: 9, border: 'none', background: '#1a1a19', color: '#ffffff', fontSize: 10, cursor: 'pointer', display: 'flex', alignItems: 'center', justifyContent: 'center', fontWeight: 700, flexShrink: 0 },
  activeBadge: { fontSize: 11, color: '#92400e', background: '#fef3c7', border: '1px solid #fde68a', borderRadius: 12, padding: '2px 8px', fontWeight: 600, maxWidth: 200, overflow: 'hidden', textOverflow: 'ellipsis', whiteSpace: 'nowrap' },
  activeFileLabel: { fontSize: 11, color: '#d97706', fontWeight: 600, padding: '4px 6px', background: '#fef3c7', border: '1px solid #fde68a', borderRadius: 6, overflow: 'hidden', textOverflow: 'ellipsis', whiteSpace: 'nowrap' },
  editBlock: { margin: '8px 0', border: '1px solid #e0ddd6', borderRadius: 8, overflow: 'hidden' },
  editHeader: { display: 'flex', alignItems: 'center', justifyContent: 'space-between', padding: '10px 16px', background: '#f3f2ee', borderBottom: '1px solid #e5e3dc' },
  editPath: { fontSize: 13, fontWeight: 600, color: '#3a3a33', overflow: 'hidden', textOverflow: 'ellipsis', whiteSpace: 'nowrap', letterSpacing: 0.1 },
  editApplyBtn: { display: 'flex', alignItems: 'center', gap: 6, background: '#ffffff', color: '#3a3a33', border: '1px solid #e0ddd6', borderRadius: 4, padding: '7px 16px', fontSize: 13, fontWeight: 500, cursor: 'pointer', boxShadow: '0 1px 2px rgba(0,0,0,0.04)' },
  editApplied: { fontSize: 11, color: '#5c5c54', fontWeight: 600 },
  editError: { fontSize: 11, color: '#a03030', fontWeight: 600, maxWidth: 260, overflow: 'hidden', textOverflow: 'ellipsis', whiteSpace: 'nowrap' },
  editCode: { margin: 0, padding: '10px 12px', fontSize: 12, lineHeight: 1.5, background: '#ffffff', color: '#3a3a33', overflowX: 'auto', whiteSpace: 'pre-wrap', wordBreak: 'break-word', maxHeight: 400, overflowY: 'auto' },
  dropupWrap: { position: 'relative' },
  dropupMenu: { position: 'absolute', bottom: '100%', right: 0, marginBottom: 8, width: 280, background: '#ffffff', border: '1px solid #e5e3dc', borderRadius: 10, boxShadow: '0 -4px 20px rgba(0,0,0,0.10)', overflow: 'hidden', zIndex: 100 },
  dropupHeader: { display: 'flex', alignItems: 'center', justifyContent: 'space-between', padding: '8px 12px', borderBottom: '1px solid #e5e3dc', background: '#f3f2ee' },
  dropupTitle: { fontSize: 12, fontWeight: 700, color: '#3a3a33' },
  dropupApplyAll: { background: '#d97706', color: '#fff', border: 'none', borderRadius: 5, padding: '3px 10px', fontSize: 11, fontWeight: 600, cursor: 'pointer' },
  dropupList: { maxHeight: 240, overflowY: 'auto', padding: '4px 0' },
  dropupItem: { display: 'flex', alignItems: 'center', justifyContent: 'space-between', padding: '6px 12px', gap: 8 },
  dropupFile: { fontSize: 12, color: '#3a3a33', fontWeight: 500, overflow: 'hidden', textOverflow: 'ellipsis', whiteSpace: 'nowrap', flex: 1 },
  dropupApplyBtn: { background: '#1a1a19', color: '#fff', border: 'none', borderRadius: 5, padding: '3px 10px', fontSize: 11, fontWeight: 600, cursor: 'pointer', flexShrink: 0 },
  dropupApplied: { fontSize: 11, color: '#166534', fontWeight: 600, flexShrink: 0 },
  dropupError: { fontSize: 11, color: '#dc2626', fontWeight: 600, flexShrink: 0 },
  editsBtn: { width: 28, height: 28, borderRadius: 8, border: 'none', background: '#e5e3dc', color: '#8c8c84', fontSize: 12, cursor: 'default', display: 'flex', alignItems: 'center', justifyContent: 'center', fontWeight: 600 },
  editsBtnActive: { background: '#fef3c7', color: '#d97706', border: '1px solid #fde68a', cursor: 'pointer' },
  paramBtn: { fontSize: 13, padding: '8px 16px', borderRadius: 4, border: '1px solid #e0ddd6', background: '#ffffff', color: '#3a3a33', cursor: 'pointer', fontWeight: 500, boxShadow: '0 1px 2px rgba(0,0,0,0.04)' },
  paramBtnOn: { background: '#000000', color: '#ffffff', border: '1px solid #000000' },
  diffViewBtn: { background: 'none', border: 'none', cursor: 'pointer', color: '#8c8c84', fontSize: 14, padding: '0 4px', borderRadius: 4, lineHeight: 1 },
  folderRowBtn: { display: 'flex', alignItems: 'center', gap: 7, background: '#ffffff', border: '1px solid #e0ddd6', borderRadius: 4, padding: '8px 16px', fontSize: 13, fontWeight: 500, color: '#3a3a33', cursor: 'pointer', boxShadow: '0 1px 2px rgba(0,0,0,0.04)' },
  folderRowMenu: { position: 'absolute', bottom: 'calc(100% + 8px)', left: 0, background: '#ffffff', border: '1px solid #e0deda', borderRadius: 12, boxShadow: '0 -4px 24px rgba(0,0,0,0.14)', overflow: 'hidden', zIndex: 1000, minWidth: 260 },
  toolCallsWrap: { marginBottom: 6 },
  toolCallsToggle: { fontSize: 10, fontWeight: 700, letterSpacing: 1, color: '#a0a098', cursor: 'pointer', marginBottom: 4, userSelect: 'none' },
  toolCallItem: { display: 'flex', gap: 8, alignItems: 'baseline', fontSize: 11, color: '#5c5c54', padding: '2px 0' },
  toolCallName: { color: '#d97706', fontWeight: 600, fontFamily: 'var(--mono)', whiteSpace: 'nowrap' },
  toolCallResult: { color: '#8c8c84', overflow: 'hidden', textOverflow: 'ellipsis', whiteSpace: 'nowrap' },
  toolCallExpanded: { background: '#f9f8f6', border: '1px solid #e5e3dc', borderRadius: 6, padding: '8px 10px', marginTop: 4, fontSize: 11, fontFamily: 'var(--mono)', whiteSpace: 'pre-wrap', maxHeight: 200, overflowY: 'auto', wordBreak: 'break-all' },
  landing: { flex: 1, display: 'flex', flexDirection: 'column', alignItems: 'center', justifyContent: 'center', padding: '0 80px', gap: 24, backgroundImage: 'radial-gradient(#e5e3dc 1px, transparent 1px)', backgroundSize: '18px 18px' },
  landingHeader: { display: 'flex', flexDirection: 'column', alignItems: 'center', gap: 6, marginBottom: 8 },
  landingKicker: { fontSize: 11, color: '#8c8c84', fontFamily: 'var(--mono)', letterSpacing: 1.2, textTransform: 'uppercase' },
  landingGreeting: { fontSize: 32, fontWeight: 500, color: '#3a3a33', display: 'flex', alignItems: 'center', gap: 12, letterSpacing: -0.5 },
  landingCaret: { color: '#d97706', fontSize: 34, fontWeight: 600, lineHeight: 1 },
  landingInputWrap: { width: '100%', maxWidth: 720 },
  landingChips: { display: 'flex', gap: 10, flexWrap: 'wrap', justifyContent: 'center', marginTop: 4 },
  landingChip: { background: '#ffffff', border: '1px solid #e0ddd6', borderRadius: 999, padding: '7px 14px', fontSize: 12, color: '#3a3a33', cursor: 'pointer', boxShadow: '0 1px 2px rgba(0,0,0,0.04)' },
  landingChipDisabled: { opacity: 0.45, cursor: 'not-allowed' },
};

export default styles;
